"""Dataclasses for the SessionManager: WindowState, ClaudeSession, Session.

Pulled out of ``session.py`` so the manager stays under the size budget
without losing the dataclasses' to_dict / from_dict round-trip logic to
the persistence module.

Public API:
  WindowState — per-tmux-window claude session id + cwd + display name.
  ClaudeSession — read-only view over a Claude transcript directory entry.
  Session — task-driven session record (the DM unit of UX).
  SessionState — the literal type alias used by Session.state.
"""

from __future__ import annotations

import secrets
import hashlib
from dataclasses import dataclass, field
from typing import Any, Literal


SessionState = Literal["active", "idle", "archived", "completed", "lost"]


@dataclass
class WindowState:
    """Persistent state for a tmux window.

    Attributes:
        session_id: Associated Claude session ID (empty if not yet detected)
        cwd: Working directory for direct file path construction
        window_name: Display name of the window
    """

    session_id: str = ""
    cwd: str = ""
    window_name: str = ""
    backend: str = "claude"
    transcript_path: str = ""

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "session_id": self.session_id,
            "cwd": self.cwd,
        }
        if self.window_name:
            d["window_name"] = self.window_name
        if self.backend != "claude":
            d["backend"] = self.backend
        if self.transcript_path:
            d["transcript_path"] = self.transcript_path
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "WindowState":
        return cls(
            session_id=data.get("session_id", ""),
            cwd=data.get("cwd", ""),
            window_name=data.get("window_name", ""),
            backend=data.get("backend", "claude"),
            transcript_path=data.get("transcript_path", ""),
        )


@dataclass
class ClaudeSession:
    """Information about a Claude Code session."""

    session_id: str
    summary: str
    message_count: int
    file_path: str
    token_total: int = 0  # input+output across all assistant turns


@dataclass
class Session:
    """A task-driven Claude Code session.

    The unit of UX in DM mode. One Session corresponds to one tmux window while
    in `active`/`idle` state; on archival the window is killed and the
    `claude_session_id` is kept so `claude --resume` can rehydrate on restore.

    Attributes:
        id: Short stable id (8 hex chars). Never changes for the lifetime of the record.
        name: Human-readable name. Auto-generated by a lightweight model, renameable.
        window_id: Current tmux window id (e.g. '@5'). Empty if archived.
        workdir: Working directory at session creation. Used as cwd for `claude --resume`.
        goal: Free-form goal description. Closed only by user via `/done`.
        state: 'active' | 'idle' | 'archived' | 'completed' | 'lost'.
        claude_session_id: Last known Claude session id (uuid). Set by SessionStart hook.
        created_at: Unix timestamp.
        last_event_at: Unix timestamp of most recent inbound or outbound activity.
        archived_at: Unix timestamp of archival, 0 while active.
        message_count: Cumulative claude turn count.
        was_lost: True if this session passed through the ``lost`` state
            before reaching its terminal state (archived/completed). Used
            to paint a "(lost)" tag in /archive so the user can tell that
            this session was never recovered from the tmux-vanish event.
    """

    id: str
    name: str
    window_id: str = ""
    workdir: str = ""
    goal: str = ""
    state: SessionState = "active"
    claude_session_id: str = ""
    created_at: float = 0.0
    last_event_at: float = 0.0
    archived_at: float = 0.0
    message_count: int = 0
    was_lost: bool = False
    backend: str = "claude"
    imported_from_backend: str = ""
    imported_from_session_id: str = ""
    screenshot_file_id: str = ""
    screenshot_pane_hash: str = ""
    screenshot_cached_at: float = 0.0
    screenshot_user_id: int = 0
    screenshot_capture_kib: int = 0
    screenshot_profile: str = ""
    preprocessed_prompt_hashes: list[str] = field(default_factory=list)
    pending_preprocessing: list[dict[str, Any]] = field(default_factory=list)
    # Non-zero only while this is the single empty prewarmed session reserved
    # for the given Telegram user. Cleared synchronously on the first request.
    default_reserve_user_id: int = 0

    @staticmethod
    def new_id() -> str:
        """Generate a fresh short id (8 lowercase hex chars)."""
        return secrets.token_hex(4)

    @property
    def dir_label(self) -> str:
        """Basename of ``workdir``, truncated to 7 chars + an ellipsis.

        Used in place of the state label when the session is active —
        "active" in the header of a session you're looking at right now
        is redundant; the directory name is the useful signal instead.
        """
        name = self.workdir.rstrip("/").rsplit("/", 1)[-1] if self.workdir else ""
        return name[:7] + "…" if len(name) > 7 else name

    def remember_preprocessed_prompt(self, text: str) -> None:
        normalized = text.strip()
        if not normalized:
            return
        digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        if digest not in self.preprocessed_prompt_hashes:
            self.preprocessed_prompt_hashes.append(digest)
            del self.preprocessed_prompt_hashes[:-256]

    def was_preprocessed_prompt(self, text: str) -> bool:
        normalized = text.strip()
        if not normalized:
            return False
        digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        return digest in self.preprocessed_prompt_hashes

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "window_id": self.window_id,
            "workdir": self.workdir,
            "goal": self.goal,
            "state": self.state,
            "claude_session_id": self.claude_session_id,
            "created_at": self.created_at,
            "last_event_at": self.last_event_at,
            "archived_at": self.archived_at,
            "message_count": self.message_count,
            "was_lost": self.was_lost,
            "backend": self.backend,
            "imported_from_backend": self.imported_from_backend,
            "imported_from_session_id": self.imported_from_session_id,
            "screenshot_file_id": self.screenshot_file_id,
            "screenshot_pane_hash": self.screenshot_pane_hash,
            "screenshot_cached_at": self.screenshot_cached_at,
            "screenshot_user_id": self.screenshot_user_id,
            "screenshot_capture_kib": self.screenshot_capture_kib,
            "screenshot_profile": self.screenshot_profile,
            "preprocessed_prompt_hashes": self.preprocessed_prompt_hashes,
            "pending_preprocessing": self.pending_preprocessing,
            "default_reserve_user_id": self.default_reserve_user_id,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Session":
        state_val = data.get("state", "active")
        if state_val not in ("active", "idle", "archived", "completed", "lost"):
            state_val = "active"
        return cls(
            id=data["id"],
            name=data.get("name", ""),
            window_id=data.get("window_id", ""),
            workdir=data.get("workdir", ""),
            goal=data.get("goal", ""),
            state=state_val,
            claude_session_id=data.get("claude_session_id", ""),
            created_at=float(data.get("created_at", 0.0)),
            last_event_at=float(data.get("last_event_at", 0.0)),
            archived_at=float(data.get("archived_at", 0.0)),
            message_count=int(data.get("message_count", 0)),
            was_lost=bool(data.get("was_lost", False)),
            backend=data.get("backend", "claude"),
            imported_from_backend=data.get("imported_from_backend", ""),
            imported_from_session_id=data.get("imported_from_session_id", ""),
            screenshot_file_id=data.get("screenshot_file_id", ""),
            screenshot_pane_hash=data.get("screenshot_pane_hash", ""),
            screenshot_cached_at=float(data.get("screenshot_cached_at", 0.0)),
            screenshot_user_id=int(data.get("screenshot_user_id", 0)),
            screenshot_capture_kib=int(data.get("screenshot_capture_kib", 0)),
            screenshot_profile=data.get("screenshot_profile", ""),
            preprocessed_prompt_hashes=[
                str(value)
                for value in data.get("preprocessed_prompt_hashes", [])
                if isinstance(value, str)
            ][-256:],
            pending_preprocessing=[
                dict(value)
                for value in data.get("pending_preprocessing", [])
                if isinstance(value, dict)
                and isinstance(value.get("request_id"), str)
                and isinstance(value.get("original"), str)
            ][-128:],
            default_reserve_user_id=int(data.get("default_reserve_user_id", 0)),
        )
